import http from "node:http"; import fs from "node:fs"; import path from "node:path";
import { chromium } from "playwright";
const DIST="/tmp/vb";
const MIME={".html":"text/html",".js":"text/javascript",".css":"text/css",".json":"application/json",".png":"image/png",".svg":"image/svg+xml",".woff2":"font/woff2"};
const srv=http.createServer((req,res)=>{let u=decodeURIComponent(req.url.split("?")[0]);let f=path.join(DIST,u);if(!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(DIST,"index.html");res.writeHead(200,{"Content-Type":MIME[path.extname(f)]||"application/octet-stream"});fs.createReadStream(f).pipe(res);});
await new Promise(r=>srv.listen(4182,r));
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1360,height:520},deviceScaleFactor:2});
const p=await ctx.newPage();
await p.goto("http://localhost:4182/#/read/40",{waitUntil:"networkidle"});
await p.waitForTimeout(800);
await p.screenshot({path:"shots/timer-closed.png",clip:{x:560,y:0,width:800,height:120}});
await p.getByTitle("Timer settings").click();
await p.waitForTimeout(400);
await p.screenshot({path:"shots/timer-menu.png",clip:{x:760,y:0,width:600,height:340}});
console.log("done");
await b.close(); srv.close();
